version: "1.0"
name: HelloWorldPipeline
description: Deploy a simple Hello, World! application

stages:
  - name: Deploy
    type: DEPLOY
    tasks:
      - name: DeployHelloWorld
        type: SHELL_SCRIPT
        delegateSelectors:
          - name: SelectorsForYourEnvironment
        properties:
          scriptSourceType: INLINE
          scriptContent: |
            #!/bin/bash
            echo "Deploying Hello, World!"
            # Add your deployment commands here

        runIf:
          - SUCCESS
